services:
  registry:
    image: registry:latest
    container_name: registry-server
    restart: always
    ports:
      - "5100:5000"
    volumes:
      - images:/var/lib/registry

volumes:
  images:
      
